### ISSUE TITLE
Criar RestController de Cliente e Serviço para listagem de um cliente

### ISSUE THREAD

**Issue by JaqueSans** [JaqueSans/helpr#1]
Criar controlador Rest;
 Criar serviço de Cliente;
 Criar métodos para endpoint de RestController;
 Vincular o repositórios de Cliente;
 Executar endpoint no Postman.

**Comment by soulcode-acad** [comment]
Trabalho muito bom quase impecável todas as notações no lugar e ótima implementação de código.  Seu código está limpo e bem feito mas acho que esqueceu de assinar os commits e ficou sem gráfico de resto foi um trabalho irretocável.

![image](https://user-images.githubusercontent.com/100297907/173602926-086fe5f8-9653-43ef-b96c-58e8926390a2.png)
